version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    ports:
      - "5434:5432"